### PR TITLE
Add ESP-13-WROOM-02

### PR DESCRIPTION
**Pull request by TurBoss**
let me know if all is correct thx

### CODE REVIEW

**Comment by jdunmire** [comment]
Please fix the following problems:
1) When filtered by keyword, the footprint for ESP-13 does not show up in the 3d column of Cvpcb. I think the $FPLIST for the ESP-13 DEF in ESP8266.lib is wrong.
missingfootprint

2) The 3d model does not match the footprint. This may be some sort of scaling problem.
esp8266_footprints_nomodels
esp8266_footprints_withmodels

**Comment by TurBoss** [comment]
sry i can't figure out why is so big hehe
i'm working on it

**Comment by TurBoss** [comment]
i fixed the $FPLIST thing but still having problems with scale

my work-flow is openscad -> mesconv/freecad(tried both) ->wings3d -> wrl

**Comment by jdunmire** [comment]
Your work flow looks like mine. Have you tried running the ESP-12.scad file through your work flow to see if you get a properly scaled .wrl file?

**Comment by TurBoss** [comment]
good idea i will do it tomorrow
thx

**Comment by TurBoss** [comment]
I have run the Esp-12 and the result is a huge model 
I don't know why hehe

my scale options are 1.0, 1.0, 1.0

**Comment by jdunmire** [comment]
I just verified my flow/files and the ESP-12 model comes out the correct size. The scale option seems like the likely difference, but I don't recall changing or setting mine in the past and I didn't make any changes for this test. Where are you setting the scale options? Is it something in Wings3d or one of the other steps?

**Comment by TurBoss** [comment]
Ok I fixed the Scale in the preferences of the footprint editor (Used the same of the ESP-12 0,393700)
now is ready for test

thx!

**Comment by TurBoss** [comment]
esp-8266

**Comment by jdunmire** [comment]
Looks good now.
I added a note to the README file about scaling.
Thank you for your contribution and effort to work through the problem.

**Comment by TurBoss** [comment]
thank you

**Pull request merged**
