### PR TITLE
Renumber ESP-12E symbol pins

### PR DESCRIPTION
**Pull request by tadas-s**
Footprint pins are numbered counter-clockwise in sequence including the
(mostly) unusable pins from CS0 (as pin9) to SCLK (as pin14).

Symbol pin sequence on the other hand maps unusable pins to range 17 to 22
([which is incorrect][1]).

[1]: https://www.esp8266.com/wiki/lib/exe/detail.php?id=esp8266-module-family&media=esp-12_pindef.png

This changes the symbol from:
selection_169

To:
selection_170

This fixes the issue #37

### CODE REVIEW

**Comment by jdunmire** [comment]
Thank you for the pull-request.
The existing numbering allows the ESP-12E to be swapped with an ESP-12 without any schematic or netlist changes. Changing the the 'correct' (and I agree it is) numbering would mean that if you want to change your design you will have to redo your schematic.

**Comment by tadas-s** [comment]
I'll take a look what's the situation with ESP-12 next week. But it sounds like they both ESP-12E and ESP-12 should have their own pcb footprints then.

**Comment by tadas-s** [comment]
Yep, from [this picture][1] for example it looks like ESP-12 has a different footprint (no pins in the bottom). So just swapping ESP-12E with ESP-12 without changing the footprint used in PCB doesn't make sense.



[1]: https://esp8266.ru/wp-content/images/esp8266-modules/ESP8266_esp-12.jpg

**Comment by slegge** [comment]
There is an 'oldNumbers' branch that already has the "correct" pin numbers, but the logic of the way it is done in master makes sense even if it doesn't match the datasheet

**Comment by jdunmire** [comment]
Perhaps we need two versions of the ESP-12e?
I'm also concerned about the side-effects of changing part. I know the present version is used in several designs and it is used as the basis (through aliases) for other versions. Any idea what would happen to those uses and aliases if the part is changed now?

**Comment by tadas-s** [comment]
Ah.. Now I get it. I used symbol from your library, but footprint - [from kicad's library][1]. My symbol and footprint library situation is also bit of a mess - packaged symbol library which does not include esp-12f symbol, and up to date footprint library which includes esp-12f footprint.

I'd still argue pin numbering is a little weird, but I'm OK with closing this PR.

edit: and this is what happens when you open a project after symbol gets updated. Kicad compares symbols against the project cache and warns / offers to save the old symbol:

selection_171

[1]: https://github.com/KiCad/RF_Modules.pretty/blob/master/ESP-12E.kicad_mod

**Comment by jdunmire** [comment]
I agree that the numbering is a bit weird, but there is some history and a rational (sort of :-) behind it.
I'm going to close this, but if you want to submit the changes with a separate name I would be open to having both variations available in the library.

Thank you for your effort.

**Pull request closed without merging**
