### PR TITLE
ESP-12E drill holes, edge drill holes

### PR DESCRIPTION
**Pull request by dfries**
This adds to the silkscreen changes with what I hope is a more accurate ESP-12E pad a drill positions.  The side pads have two drill holes one through the pad and one on the edge, the bottom only has them in the edge.  This is the best representation in kicad for them.

As the ESP-12E can have pins added and used as a through hole device, or be soldered to the edges and used as an SMD device, should this really be two separate models, with one for each use case?

### CODE REVIEW

**Comment by jdunmire** [comment]
Would it be possible to use (copy) the pads and holes from the ESP-12? They work well for at least three mounting choices: 
- hand soldered surface mount (because the footprints extend beyond the module where they can be touched with a soldering iron).
- reflow surface mount (Though I haven't tried this and I would be concerned about the reflow effect on the ESP-12E).
- through hole as you note.

**Comment by dfries** [comment]
I tried to just copy them over (external editor), but the ESP-12 and ESP-12E have different origins.  The ESP-12 is in the center of pad drill hole 1, ESP-12E has it in the center of the SMD pad (which is basically on the board edge).  I could duplicate ESP-12 to ESP-12E renumber and add the bottom 9 through 14, which brings up the other problem.  Any suggestion on how to handle 9 through 14?  Kicad doesn't allow the edge drill hole, to it the drill hole must be inside of the pad.  Looks like the best it could do is put the drill hole almost at the edge.  It doesn't allow not having a drill hole for a through hole pad, and it would look funny if those were SMD pads as compared to the others, but they are all through hole it just has one less hole.

**Comment by jdunmire** [comment]
I see to options:
1. Keep the original oval surface mount pads.
2. Rotate one of the ESP-12 pads  with the hole and just leave the hole offset under the ESP-12E.

(I ignore the 1/2 holes because I consider them an aid to soldering and not a real mounting option.)

I slightly prefer 1 because you couldn't really add pins to 9-14, but 2 allows access from the underside without dropping a via.

**Comment by dfries** [comment]
2 sounds more accurate to me, I could just make the drill hole very small and almost no one will know it was there.  I'll assume anyone who s actually making a board for the ESP8266 will start from scratch because it is missing all the wiring, LED, antenna, and such, and so a nearly zero sized hole shouldn't matter.  I've added some silkscreen to my modules to indicate how the LED is attached so as a reminder that the pin is already pulled up from the LED.
Okay, so you prefer 1, I'm going to eat and if I don't hear anything else that's how I'll make it up.

**Comment by jdunmire** [comment]
I guess it is a point of view. I'm looking at making a footprint that will work well for boards that will have an ESP-x mounted as a module. I hadn't given much thought to trying to recreate the module itself.
If one did try to recreate the module, I think the design would be a kicad project, not a library.

**Comment by dfries** [comment]
5124f6977d904615d4b7bed6589f54d1e1eb2ba2 now has the ESP-12E that matches ESP-12 only with the addition of the end pads and renumbering the one side.  This does change the origin for the footprint, but that can't be helped to get the two modules to be as similar as they actually are.

**Comment by jdunmire** [comment]
Thank you for making the changes and contributing.

**Pull request merged**
